name: Build and Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release Tag (e.g. v1.0.0)'
        required: true
        type: string

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    # Required permission to create a Github Release
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Build AutoSave Extension
        run: python build_oxt.py
        
      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.release_tag }}
          name: Release ${{ github.event.inputs.release_tag }}
          files: dist/AutoSave.oxt
          generate_release_notes: true
